<!doctype html>
<html lang="zh-CN">
<head>
    <title>员工端数据分析系统</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>登录</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-sign_in {
            max-width: 330px;
            padding: 15px;
        }

        .form-sign_in .form-floating:focus-within {
            z-index: 2;
        }

        .form-sign_in input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-sign_in input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
</head>
<body class="text-center">

<main class="form-sign_in w-100 m-auto" id="app">
    <form action="/login" method="post">
        <h1 class="h3 mb-3 fw-normal">登录</h1>

        <div class="form-floating">
            <input type="text" class="form-control" id="floatingInput" name="username" placeholder="账号">
            <label for="floatingInput">账号</label>
        </div>
        <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="密码">
            <label for="floatingPassword">密码</label>
        </div>

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="remember-me"> 记住我
            </label>
        </div>
        <button type="submit" class="w-100 btn btn-lg btn-primary">登录</button>
    </form>
</main>
<script>

</script>

</body>
</html>
